version: "v5678"
services:
  omics:
    image: omics_r43:v2.0
    ports:
       - 6322:6322
    volumes:
       - /data1:/data1
    networks:
      meta_net:
        ipv4_address: 172.16.1.4
  web:
    image: smetabobank:v5.1
    pid: host
    privileged: true
    ports:
       - 8085:8088
    volumes:
       - /metabobank_data:/metabobank_data
       - /mongodb:/mongodb
       - /data1:/data1
    environment:
       - TZ=Asia/Shanghai
    command: /start.sh
    networks:
      meta_net:
        ipv4_address: 172.16.1.2
  mongodb:
    image: mongod:v1234"172.16.1.0/24" 